# Generated by Django 3.1.7 on 2021-03-19 19:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=45)),
                ('l_name', models.CharField(max_length=45)),
                ('pword_salt', models.CharField(max_length=10, null=True)),
                ('pword_hash', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterestRate',
            fields=[
                ('acct_type', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='RequestReset',
            fields=[
                ('reset_id', models.AutoField(primary_key=True, serialize=False)),
                ('verification_string', models.CharField(max_length=45)),
                ('expires', models.DateTimeField(default=datetime.datetime(2021, 3, 19, 15, 52, 4, 388300), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='grizz_bank.client')),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='grizz_bank.client')),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Username',
            fields=[
                ('username', models.CharField(max_length=45)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='grizz_bank.client')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('acct_id', models.AutoField(primary_key=True, serialize=False)),
                ('acct_bal', models.DecimalField(decimal_places=2, max_digits=7)),
                ('acct_type', models.CharField(max_length=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grizz_bank.client')),
            ],
        ),
    ]
