# Generated by Django 3.1.7 on 2021-04-02 15:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(default='', max_length=45)),
                ('l_name', models.CharField(default='', max_length=45)),
                ('pword_salt', models.CharField(max_length=10, null=True)),
                ('pword_hash', models.CharField(max_length=300, null=True)),
                ('email', models.CharField(default='', max_length=50)),
                ('username', models.CharField(default='', max_length=45)),
                ('phone_number', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='InterestRate',
            fields=[
                ('acct_type', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='RequestReset',
            fields=[
                ('reset_id', models.AutoField(primary_key=True, serialize=False)),
                ('verification_string', models.CharField(max_length=45)),
                ('expires', models.DateTimeField(default=datetime.datetime(2021, 4, 2, 11, 44, 9, 207091), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='UsernameArchive',
            fields=[
                ('archive_uname_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45)),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grizz_bank.client')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumberArchive',
            fields=[
                ('archive_phone_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=10)),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grizz_bank.client')),
            ],
        ),
        migrations.CreateModel(
            name='EmailArchive',
            fields=[
                ('archive_email_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grizz_bank.client')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('acct_id', models.AutoField(primary_key=True, serialize=False)),
                ('acct_bal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('acct_type', models.CharField(max_length=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grizz_bank.client')),
            ],
        ),
    ]
