# Generated by Django 3.1.7 on 2021-04-16 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grizz_bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestreset',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 16, 15, 43, 13, 505949), editable=False),
        ),
        migrations.AlterField(
            model_name='requestreset',
            name='verification_string',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
