# Generated by Django 3.1.7 on 2021-03-19 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grizz_bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acct_bal',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='requestreset',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 19, 15, 52, 56, 817444), editable=False),
        ),
    ]
