# Generated by Django 3.1.7 on 2021-04-16 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grizz_bank', '0002_auto_20210416_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(default='', max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='requestreset',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 16, 16, 42, 20, 399479), editable=False),
        ),
    ]
